PEAR-1819: Handle exceptions related to login window
NCI-GDC/gdc-frontend-framework pull request #1019
Opened 2024-03-18 17:21 UTC by paribartandhakal

## Description
Adding a try-catch blok.

## Checklist
- [ ] Added proper unit tests
- [ ] Left proper TODO messages for any remaining tasks
- [ ] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)

2024-03-18 19:12 UTC, wteouchicago commented
this worked for me. I didn't see the errors in the console and I was able to log in, download some CA data, and log out without anything unusual happening. 👍

2024-03-20 16:32 UTC, amlehman approved these changes

2024-03-20 16:32 UTC, amlehman commented on packages/portal-proto/src/features/layout/auth/openAuthWindow.ts
> +          // just want to catch it and not reject it
Could you add a little more context/reasoning to this comment?

2024-03-20 17:05 UTC, craigrbarnes requested changes
Looks fine, but I agree with Amy's comment.

2024-03-20 17:41 UTC, paribartandhakal commented
> Looks OK, but I agree with Amy's request for more context in the comment.

@amlehman @craigrbarnes  I just updated it. Please let me know if it's clear now.

2024-03-29 14:53 UTC, craigrbarnes approved these changes

2024-03-29 14:53 UTC, merged