Support creating a single-case cohort in ProteinPaint, OncoMatrix, Gene Expression tools
NCI-GDC/gdc-frontend-framework pull request #1031
Opened 2024-03-21 21:57 UTC by siosonel

## Description

Closes https://gdc-ctds.atlassian.net/browse/SV-2417

## Checklist

- [ ] Added proper unit tests
- [ ] Left proper TODO messages for any remaining tasks
- [ ] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)

2024-03-25 22:37 UTC, craigrbarnes approved these changes

2024-03-26 14:57 UTC, craigrbarnes requested changes
There is build error:
```
src/features/proteinpaint/GeneExpressionWrapper.tsx(67,15): error TS2322: Type 'string' is not assignable to type 'readonly (string | number)[]'.
src/features/proteinpaint/OncoMatrixWrapper.tsx(68,15): error TS2322: Type 'string' is not assignable to type 'readonly (string | number)[]'.
src/features/proteinpaint/ProteinPaintWrapper.tsx(61,15): error TS2322: Type 'string' is not assignable to type 'readonly (string | number)[]'.
npm ERR! Lifecycle script `compile` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: portal-proto@2.12.0 
npm ERR!   at location: /builds/8Sbmo3DL/2/nci-gdc/front-end/gdc-frontend-framework/packages/portal-proto 
```

2024-03-26 21:18 UTC, siosonel commented
> There is build error:
> 
> ```
> src/features/proteinpaint/GeneExpressionWrapper.tsx(67,15): error TS2322: Type 'string' is not assignable to type 'readonly (string | number)[]'.
> src/features/proteinpaint/OncoMatrixWrapper.tsx(68,15): error TS2322: Type 'string' is not assignable to type 'readonly (string | number)[]'.
> src/features/proteinpaint/ProteinPaintWrapper.tsx(61,15): error TS2322: Type 'string' is not assignable to type 'readonly (string | number)[]'.
> npm ERR! Lifecycle script `compile` failed with error: 
> npm ERR! Error: command failed 
> npm ERR!   in workspace: portal-proto@2.12.0 
> npm ERR!   at location: /builds/8Sbmo3DL/2/nci-gdc/front-end/gdc-frontend-framework/packages/portal-proto 
> ```

@craigrbarnes These build errors are not showing up when I run `npx tsc` locally. The cohort filter entry is also a `string`, and I was following the code in [Wendy's example in the JIRA ticket](https://github.com/NCI-GDC/gdc-frontend-framework/blob/develop/packages/portal-proto/src/features/cases/CasesView/CasesCohortButton.tsx#L119), so I'm pretty sure the type check here is not correct. I tried to change the files, hoping to trigger another build/check, but the error is still there. I can try to fork a new branch and open another PR to test.

2024-03-26 23:17 UTC, craigrbarnes approved these changes

2024-03-26 23:18 UTC, merged