PEAR-1825: Fix Mutation Frequency - Survival Plot is not updating
NCI-GDC/gdc-frontend-framework pull request #1073
Opened 2024-04-10 16:09 UTC by ocshawn

## Description
- Fix Mutation Frequency - Survival Plot is not updating

## Checklist

- [x] Added proper unit tests
- [x] Left proper TODO messages for any remaining tasks
- [x] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)

2024-04-10 21:31 UTC, amlehman approved these changes

2024-04-10 22:34 UTC, wteouchicago requested changes
Things are not working as expected. Now I can't seem to change the survival plot because it keeps switching back to the top gene. Steps:
- use lung cohort from home page (for ease)
- go to Mutation Frequency, let it finish loading
- on the Genes table, click the Survival button for MUC16 (or some non-top gene)
- notice it'll switch back to TP53 (the top gene)

Same on the mutations side.

2024-04-11 21:31 UTC, wteouchicago commented
works great for me! thanks for fixing 👍

2024-04-11 21:31 UTC, wteouchicago approved these changes

2024-04-11 22:13 UTC, merged