QA-2070 Minor fixes related to CI setup
NCI-GDC/gdc-frontend-framework pull request #958
Opened 2024-02-01 15:00 UTC by uc-pperumala

## Description
- Add IP for `qa_orange`
- If `holmes-py` is found in dir path, then return that as parent, otherwise, return the parent where `.git` is found
- Update test files where `parent_dir()` is used

## Checklist
- Run tests: `gauge run specs`
- Ensure that the tests where .tsv are uploaded are working as expected
- Ensure that the tests where `/resources` and `/download` directories are used are working

2024-02-01 16:03 UTC, bpierce01 requested changes
Tests that use files in 'resources' are not working. They are working in the main branch. I am receiving this error when trying to run any of them. The "holmes-py" is missing in the file path for grabbing resources: 

File "/Users/brentpierce/Documents/GitHub/gdc-frontend-framework/holmes-py/venv/lib/python3.10/site-packages/playwright/_impl/_set_input_files_helpers.py", line 50, in <listcomp>
      os.stat(f).st_size > SIZE_LIMIT_IN_BYTES
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/brentpierce/Documents/GitHub/gdc-frontend-framework/resources/cohort_bar/organoid.tsv'

2024-02-15 18:01 UTC, bpierce01 reviewed
Delete the "APP_ENDPOINT_PROD_SOFT_LAUNCH". I ran the code again, and the tests that use resources or downloads folder are working.

2024-02-15 18:01 UTC, bpierce01 commented on holmes-py/env/default/default.properties
>  APP_ENDPOINT_PROD_SOFT_LAUNCH = https://portal.gdc.cancer.gov
We can delete "APP_ENDPOINT_PROD_SOFT_LAUNCH" now

2024-02-16 16:25 UTC, bpierce01 commented on holmes-py/env/default/default.properties
>  APP_ENDPOINT_LOCAL = http://localhost:3000/v2
This also should be: APP_ENDPOINT_LOCAL = http://localhost:3000

2024-02-23 17:40 UTC, bpierce01 requested changes
The readme at holmes-py/docs/test-framework.md needs to be updated as well (to reflect the updates of default.properties)

2024-02-23 19:37 UTC, bpierce01 approved these changes
Documentation looks good. Pulled branch and ran a couple tests and they passed. Approving

2024-02-23 20:42 UTC, ManjunathJayanna approved these changes
Executed tests, they are some failures, but Brent previously has noted familiarity on the same.

2024-02-26 19:57 UTC, uc-pperumala commented
@craigrbarnes could you please merge this whenever you get a chance?

2024-02-26 22:45 UTC, craigrbarnes approved these changes

2024-02-26 22:45 UTC, merged