Qa 2136 condensed cohort creation
NCI-GDC/gdc-frontend-framework pull request #975
Opened 2024-02-14 21:41 UTC by bpierce01

## Description
- Condensed test step for creating and saving a cohort with specified filters
- Test step for for creating and saving a cohort with randomized filters

2024-02-14 21:42 UTC, bpierce01 commented
Let me know if you have any questions about the logic/loops for the randomized steps. I tried to leave comments explaining all the steps.

2024-02-15 01:54 UTC, uc-pperumala commented on holmes-py/step_impl/apps/gdc_data_portal_v2/pages/cohort_builder_page.py
> +            if self.is_visible(no_data_available_locator):
`return True if self.is_visible(no_data_available_locator) else Fase`

2024-02-15 02:08 UTC, uc-pperumala requested changes
Seeing some failures (1 step failing for multiple scenarios)

2024-02-15 16:40 UTC, bpierce01 commented on holmes-py/step_impl/apps/gdc_data_portal_v2/pages/cohort_builder_page.py
> +            if self.is_visible(no_data_available_locator):
Addressed!

2024-02-15 16:40 UTC, bpierce01 commented
> ```
> # Cohort Bar - Save, Switch, Delete Cohort
>   ## Navigate to Cohort Builder  ✔ ✔
>   ## Save a cohort for the first time    ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔
>   ## Save a cohort for the second time   ✔ ✔ ✔ ✔ ✘
>         Failed Step: Perform action and validate modal text
>         Specification: specs/gdc_data_portal_v2/cohort_bar/general_cohort_functions.spec:41
>         Error Message: The text 'Cohort has been saved' is NOT present
>         Stacktrace: 
>         Traceback (most recent call last):
>           File "/Users/pramodperumala/.local/lib/python3.8/site-packages/getgauge/executor.py", line 33, in execute_method
>             step.impl(*params)
>           File "/Users/pramodperumala/Software/gdc-frontend-framework/holmes-py/step_impl/apps/gdc_data_portal_v2/step_defs/generic_steps.py", line 513, in click_named_button_in_modal_and_wait_for_temp_message_text
>             assert is_cohort_message_present, f"The text '{v[1]}' is NOT present"
>         AssertionError: The text 'Cohort has been saved' is NOT present
>         
>   ## Switch cohorts      ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔
>   ## Delete a saved cohort       ✔ ✔ ✔ ✔
>   ## Delete an unsaved cohort    ✔ ✔ ✔ ✔ ✔
>   ## Random filters cohort creation      ✔
>   ## Shortened cohort saving     ✔
> 
> Successfully generated html-report to => /Users/pramodperumala/Software/gdc-frontend-framework/holmes-py/reports/html-report/index.html
> 
> Specifications: 1 executed      0 passed        1 failed        0 skipped
> Scenarios:      8 executed      7 passed        1 failed        0 skipped
> 
> Total time taken: 3m43.655s
> Updates are available. Run `gauge update -c` for more info.
> (venv) pramodperumala@Pramods-MacBook-Pro holmes-py % gauge run specs/gdc_data_portal_v2/cohort_bar/general_cohort_functions.spec
> 
> Python: 3.8.9
> E0214 20:03:59.155054000 123145513623552 fork_posix.cc:76]             Other threads are currently calling into gRPC, skipping fork() handlers
> E0214 20:04:01.595433000 123145513623552 fork_posix.cc:76]             Other threads are currently calling into gRPC, skipping fork() handlers
> # Cohort Bar - Save, Switch, Delete Cohort
>   ## Navigate to Cohort Builder  ✔ ✔
>   ## Save a cohort for the first time    ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔
>   ## Save a cohort for the second time   ✔ ✔ ✔ ✔ ✘
>         Failed Step: Perform action and validate modal text
>         Specification: specs/gdc_data_portal_v2/cohort_bar/general_cohort_functions.spec:41
>         Error Message: The text 'Cohort has been saved' is NOT present
>         Stacktrace: 
>         Traceback (most recent call last):
>           File "/Users/pramodperumala/.local/lib/python3.8/site-packages/getgauge/executor.py", line 33, in execute_method
>             step.impl(*params)
>           File "/Users/pramodperumala/Software/gdc-frontend-framework/holmes-py/step_impl/apps/gdc_data_portal_v2/step_defs/generic_steps.py", line 513, in click_named_button_in_modal_and_wait_for_temp_message_text
>             assert is_cohort_message_present, f"The text '{v[1]}' is NOT present"
>         AssertionError: The text 'Cohort has been saved' is NOT present
>         
>   ## Switch cohorts      ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔
>   ## Delete a saved cohort       ✔ ✔ ✔ ✔
>   ## Delete an unsaved cohort    ✔ ✔ ✔ ✔ ✔
>   ## Random filters cohort creation      ✔
>   ## Shortened cohort saving     ✔
> 
> Successfully generated html-report to => /Users/pramodperumala/Software/gdc-frontend-framework/holmes-py/reports/html-report/index.html
> 
> Specifications: 1 executed      0 passed        1 failed        0 skipped
> Scenarios:      8 executed      7 passed        1 failed        0 skipped
> 
> Total time taken: 3m29.172s
> ```
> 
> Seeing some failures (1 step failing for multiple scenarios)

Yes that is a known and expected failure. There is a front-end ticket for a fix.

2024-02-15 17:16 UTC, uc-pperumala approved these changes
Approved.

2024-02-15 17:42 UTC, wteouchicago approved these changes

2024-02-16 15:51 UTC, merged