T/qa 2157/apply black
NCI-GDC/gdc-frontend-framework pull request #984
Opened 2024-02-21 19:30 UTC by uc-pperumala

## Description

## Checklist

- [ ] Added proper unit tests
- [ ] Left proper TODO messages for any remaining tasks
- [ ] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)

2024-02-21 19:33 UTC, bpierce01 requested changes
There are merge conflicts

2024-02-21 23:08 UTC, uc-pperumala commented
Resolved merge conflics.

@ManjunathJayanna and @bpierce01 I need both of

> There are merge conflicts

@bpierce01 fixed. should be good now.

2024-02-21 23:36 UTC, bpierce01 requested changes
Getting a compile error when trying to run: 
Failed to parse /gdc_data_portal_v2/pages/cohort_bar.py: Error, got an unexpected token EQUAL here:

  93         """
  94         # Concatenate the full text of the filter being checked for
  95         full_query_filter = filter + values
  96         full_query_filter_locator = CohortBarLocators.TEXT_COHORT_QUERY_FILTER(            
  97 full_query_filter, position        
  98 )
  99         
 100         = <---- here

2024-02-23 16:29 UTC, bpierce01 commented on holmes-py/step_impl/apps/gdc_data_portal_v2/pages/cohort_bar.py
> -        is_full_query_filter_locator_visible = self.is_visible(full_query_filter_locator)
This variable "is_full_query_filter_locator_visible" was erroneously removed

2024-02-23 17:33 UTC, bpierce01 approved these changes
Ran regression, did not find any problems. Code formatting looks fine. Approving

2024-02-26 19:58 UTC, uc-pperumala commented
@craigrbarnes could you please merge this whenever you have a chance?

2024-02-26 22:46 UTC, merged